#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# set RELATIVE to the next higher directory 
RELATIVE := ..

# other places to look for files for this project
SEARCH  := $(RELATIVE)/lib

# source files in this project (main.cpp is automatically assumed)
SOURCES := radioReceiver.cpp

# header files in this project
HEADERS := radioReceiver.hpp potmeterInput.hpp


# and defer to the appropriate Makefile.* there
include $(RELATIVE)/Makefile.due
